### ISSUE TITLE
Problem on transaction signature with new user (ledger multisig)

### ISSUE THREAD

**Issue by antoninobf** [gnosis/MultiSigWallet#80]
Hello,

We are using a contract with multsig signature on our ledger.
Since 1 month, we can add a new user and he cannot sign any transactions.

Can you help us ?

Thanks,
Antonino

**Comment by denisgranha** [comment]
Hello @antoninobf which version are you using of the interface (desktop, web, etc)

What OS are you running?

What version of firmware ledger runs?

Thanks,

**Comment by denisgranha** [comment]
Hello @antoninobf this is solved in the last version https://github.com/gnosis/MultiSigWallet/releases/tag/v1.2.1 

Sorry for the inconvenience

**Comment by antoninobf** [comment]
Hello,

I will test and let you know.



<https://www.bochslerfinance.com/>


*Antonino Ristagno **antonino@bochslerfinance.com*
<antonino@bochslerfinance.com>



Bochsler Finance

Gotthardstrasse 26

6300 Zoug, Switzerland

T +41 78 812 35 78 <+41788123578>

This electronic message and its accompanying attachments(if any) may
contain information that is confidential or otherwise legally privileged.
Such information is intended solely for the individual or entity to whom it
is addressed. If you are not the intended recipient of this message, please
notify the sender immediately and be aware that any disclosure, copying,
distribution, or use of this message or its accompanying attachments (if
any) is prohibited.

2018-02-24 21:26 GMT+01:00 Denis Granha <notifications@github.com>:

**Comment by antoninobf** [comment]
Hello,

We tested right now and it still doesn't work.
Have a look on the picture below for the error message :

[image: Images intégrées 1]

Thanks in advance,

<https://www.bochslerfinance.com/>


*Antonino Ristagno **antonino@bochslerfinance.com*
<antonino@bochslerfinance.com>



Bochsler Finance

Gotthardstrasse 26

6300 Zoug, Switzerland

T +41 78 812 35 78 <+41788123578>

This electronic message and its accompanying attachments(if any) may
contain information that is confidential or otherwise legally privileged.
Such information is intended solely for the individual or entity to whom it
is addressed. If you are not the intended recipient of this message, please
notify the sender immediately and be aware that any disclosure, copying,
distribution, or use of this message or its accompanying attachments (if
any) is prohibited.

2018-02-26 10:18 GMT+01:00 Antonino Ristagno <antonino@bochslerfinance.com>:

**Comment by denisgranha** [comment]
it's the option browser support disabled in the ledger? @antoninobf

**Comment by antoninobf** [comment]
yes it was disabled.



<https://www.bochslerfinance.com/>


*Antonino Ristagno **antonino@bochslerfinance.com*
<antonino@bochslerfinance.com>



Bochsler Finance

Gotthardstrasse 26

6300 Zoug, Switzerland

T +41 78 812 35 78 <+41788123578>

This electronic message and its accompanying attachments(if any) may
contain information that is confidential or otherwise legally privileged.
Such information is intended solely for the individual or entity to whom it
is addressed. If you are not the intended recipient of this message, please
notify the sender immediately and be aware that any disclosure, copying,
distribution, or use of this message or its accompanying attachments (if
any) is prohibited.

2018-02-26 16:48 GMT+01:00 Denis Granha <notifications@github.com>:

**Comment by denisgranha** [comment]
okay thanks for checking, can you post the picture directly to github? seems to be broken the link, it's MacOS I assume? or windows?

**Comment by antoninobf** [comment]
ok
it's windows



<https://www.bochslerfinance.com/>


*Antonino Ristagno **antonino@bochslerfinance.com*
<antonino@bochslerfinance.com>



Bochsler Finance

Gotthardstrasse 26

6300 Zoug, Switzerland

T +41 78 812 35 78 <+41788123578>

This electronic message and its accompanying attachments(if any) may
contain information that is confidential or otherwise legally privileged.
Such information is intended solely for the individual or entity to whom it
is addressed. If you are not the intended recipient of this message, please
notify the sender immediately and be aware that any disclosure, copying,
distribution, or use of this message or its accompanying attachments (if
any) is prohibited.

2018-02-26 17:00 GMT+01:00 Denis Granha <notifications@github.com>:

**Comment by antoninobf** [comment]
![photo_2018-02-26_16-38-30](https://user-images.githubusercontent.com/36630397/36680837-2caae3a6-1b17-11e8-9a21-be7bb853569b.jpg)
here the error message

**Comment by antoninobf** [comment]
posted on github



<https://www.bochslerfinance.com/>


*Antonino Ristagno **antonino@bochslerfinance.com*
<antonino@bochslerfinance.com>



Bochsler Finance

Gotthardstrasse 26

6300 Zoug, Switzerland

T +41 78 812 35 78 <+41788123578>

This electronic message and its accompanying attachments(if any) may
contain information that is confidential or otherwise legally privileged.
Such information is intended solely for the individual or entity to whom it
is addressed. If you are not the intended recipient of this message, please
notify the sender immediately and be aware that any disclosure, copying,
distribution, or use of this message or its accompanying attachments (if
any) is prohibited.

2018-02-26 17:03 GMT+01:00 Antonino Ristagno <antonino@bochslerfinance.com>:
